version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: bimetri_container
    environment:
      POSTGRES_DB: bimetri
      POSTGRES_USER: bimetri
      POSTGRES_PASSWORD: bimetri
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
