# Server & Error Configuration
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

# Database Configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bimetri
    username: bimetri
    password: bimetri
    driver-class-name: org.postgresql.Driver

# JPA Configuration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

# Log Configuration

logging:
  file:
    name: log/bimetri.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    org.springframework.web: WARN
    org.hibernate: info
    org.rent-a-car: debug

# Actuator  Configuration

management: #actuator
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    shutdown:
      enabled: true

# Application info Configuration

info:
  application:
    name: 'Bimetri Backend App'
    description: 'This is Bimetri Backend Project'
    version: '@project.version@'

# Swagger-ui custom path Configuration

springdoc:
  swagger-ui:
    path: /bimetri-ui